### ISSUE TITLE
generic --cloud-type not working

### ISSUE THREAD

**Issue by casperdcl** [iterative/cml#1145]
`cml runner ... --cloud=aws --cloud-type=m+t4` doesn't work:

```python
{"level":"error",
 "message":"terraform error: Error: Failed creating the machine: Not able to decode: operation error EC2: RunInstances,
https response error StatusCode: 400,
RequestID: 622a6bc7-75c5-47d1-83ae-76f8f9029186,
api error InvalidParameterValue: Invalid value 'm+t4' for InstanceType."}
```

meanwhile `cml runner ... --cloud=aws --cloud-type=m --cloud-gpu=t4`:

```python
{"level":"error",
 "message":"terraform error: Error: Failed creating the machine: Not able to decode: operation error EC2: RunInstances,
https response error StatusCode: 400,
RequestID: dcc5278c-7eda-467a-b142-20c4d3de10f1,
api error InvalidParameterValue: Invalid value 'm' for InstanceType."}
```

does CML not work with [TPI generic-machine-types](https://registry.terraform.io/providers/iterative/iterative/latest/docs/guides/generic-machine-types)?

**Comment by dacbd** [comment]
yes, and no.

Something does need to be improved as what exists is clearly not clear :upside_down_face: 

I was previously in favor of splitting out these mappings to something more consolidated but unfortunately, that was cut and these "helper types" are all completely separate in their respective providers.  So something like `m+t4` which may work on one does not work on others.

for example, `m+t4` is missing from all the providers see: [AWS](https://github.com/iterative/terraform-provider-iterative/blob/64d3d0d2fcea90cd785a0baf44fbcbb956392957/iterative/aws/provider.go#L463-L482 ) and [azure](https://github.com/iterative/terraform-provider-iterative/blob/64d3d0d2fcea90cd785a0baf44fbcbb956392957/iterative/azure/provider.go#L416-L435): 

additionally the `--cloud-gpu` is essentially only functional with GCP in  a way that I would expect since azure and AWS have separate machine types with predetermined GPUs but GCP allows you to more explicitly set something, see: #1049

**Comment by casperdcl** [comment]
...and iterative/cml.dev#251

**Comment by dacbd** [comment]
@casperdcl with https://github.com/iterative/terraform-provider-iterative/pull/718 the next tpi release with resolve the error you found here, with https://github.com/iterative/cml.dev/issues/251 as its own issue that should still be addressed I think we can close this one, but I'll leave that to you.

**Comment by casperdcl** [comment]
Thanks; happy to close here :)
