### ISSUE TITLE
--cloud-startup-script running after CML runner setup prevents CML runner running in coporate environment

### ISSUE THREAD

**Issue by jancrichter** [iterative/cml#1364]
Dear CML devs,

Launching a CML runner on AWS EC2 is currently impossible for us, because some environment customisation must take place before CML can run its own setup scripts and ther eis no way around that.

We would need CML runner to either run the cloud startup script before anything else, or provide a way to either customize the AMI used by CML or provide our own.

This is currently keeping us from using CML in the corporate context.

Best regards,
Jan

**Comment by dacbd** [comment]
There is a hidden option `--cloud-image` you can pass the name of your custom ami image. For example, our value `iterative-cml`. We will likely have limited ability to help debug any instance-related issues you may have if you opt to use this method.

what type of environment customization need to happen before cml executes?

**Comment by jancrichter** [comment]
Thanks. Why hide this option from documentation?

In terms of customisation, special networking settings have to be applied as our VPCs don't have external connectivity for security reasons.

**Comment by dacbd** [comment]
it is hidden because it can make it very difficult to diagnose users' issues as we will likely have no idea what the environment is that things might be executed in. As well as likely making it impossible for us to reproduce a reported error. Additionally, you could choose a base image that is simply not compatible with some assumptions we make in our base setup script. (if you select an ubuntu image it *should* be fine)

However, it exists because it is sometimes asked for, and so we have provided it with the caveat that you understand the above.

**Comment by jancrichter** [comment]
Setting up networking according to our needs would be the preferred method. However, I do not currently see a way to achieve this. 

Is this something that could realistically be expected to be implemented? I would expect other corporate users facing a similar need.

**Comment by dacbd** [comment]
Im not sure still what your requirements are? 

You can `--cloud-aws-security-group=my-security-group` (which can target a specific vpc in you account) and `--cloud-aws-subnet=subnet-qwerty` 

see an example of its use here: https://github.com/iterative/cml-playground/blob/main/workflows/cml-1121.yml

**Comment by 0x2b3bfa0** [comment]
Closing as stale after ~3 months; feel free to reopen if the suggested solutions aren't enough for your use case.
