### ISSUE TITLE
Experiment camparison

### ISSUE THREAD

**Issue by lipovsek** [iterative/cml#188]
Great project, tested it a bit. I would love to set up POC for gitlab on comparing metrics of experiments(or merge requests). Is this in line with authors ideas of this library?

**Comment by DavidGOrtega** [comment]
Hi @lipovsek! 
Could you please elaborate a bit more?

**Comment by elleobrien** [comment]
It seems like a good place to start would be in our DVC use case- I'm pointing you to a sample merge request on GitLab where metrics are compared across experiments. A few metrics diffs are reported in a table, and then loss functions from `master` and the head of the feature branch are plotted

 https://gitlab.com/iterative.ai/cml-dvc-case/-/merge_requests/6

We think DVC provides a good functionality for this, because of built in features like `dvc metrics diff` and `dvc plots diff` that let you compare across commits. If you don't want to use DVC, you can use `git show` to copy previous (or parallel) versions of a metrics file into a temporary file and print the outputs in a table. I did that in [this use case here, line 57](https://gitlab.com/iterative.ai/cml-cloud-case/-/blob/master/.gitlab-ci.yml)

**Comment by elleobrien** [comment]
Hi @lipovsek, a quick update- we made a video tutorial about comparing models across branches. Hope this helps show how we would use CML + DVC together to do a `git diff` of sorts for experiments.

https://youtu.be/xPncjKH6SPk
