### ISSUE TITLE
CML docker version tagging

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#217]
NPM is registering the versions properly, however DockerHub is not.
Be able to pin the exact version if CML is important to warranty the reproducibility of the workflow. Changes in ```latest``` may break existing workflows and enforces us to work with backward compatibility

**Comment by hsharrison** [comment]
I brought this up [her](https://github.com/iterative/dvc/issues/2774) but was redirected here.

We would like to have a pinned version.

In the other issue I was asked what the pain point was, and it's true that you all have not made any backwards incompatibilities. So the pain point is merely that we have policies about pinning images and not having versions forces us to break that policy and then explain a comment why it's pinned `latest`, having team members get confused about this every now and then and think someone made a mistake (e.g. if they see `cml:latest` in the CI logs), etc.

Maybe there will never be a problem and nothing will ever be broken but it does take some "cognitive load" to remember why it's not version pinned.

**Comment by DavidGOrtega** [comment]
👋 @hsharrison I will review this soon

**Comment by DavidGOrtega** [comment]
With DVC 2.0 breaking changes this is actually very important.
@0x2b3bfa0 we should even review if this is not a stopper for the latest release

**Comment by hsharrison** [comment]
> With DVC 2.0 breaking changes this is actually very important.
> @0x2b3bfa0 we should even review if this is not a stopper for the latest release

Oh yeah, have you guys already updated the image? 😬  I can tell you soon if it is causing any problems...

**Comment by 0x2b3bfa0** [comment]
@hsharrison, no worries: we haven't (yet) and we won't without considering the implications.

I wonder if we could avoid shipping DVC with the base CML containers and ask users to explicitly install it, following the reasoning behind https://github.com/iterative/dvc/issues/2774. Another option would be shipping the two most recent major versions, but the bloat might be worse than the benefits.

**Comment by DavidGOrtega** [comment]
@0x2b3bfa0 lets attack this definitely.

We have to tag with:
 - CUDA 10 and 11
 - Python 3
 - DVC 2
  
So the image could be
 - dvcorg/cml:cuda10-python-dvc2:{version}
 - dvcorg/cml:cuda11-python3-dvc:{version}
 
We can also for easiness and clarity get rid off elgohr/Publish-Docker-Github-Action. Has served us very well but for this might be easier for us to all without it like we are tagging later on.

We can do also #383

**Comment by 0x2b3bfa0** [comment]
About the Docker tagging, I wouldn't mind spending some time deprecating all the legacy images and tags (if any), and setting up automated tagging for the next releases, but the main issue is what to ship and how to ship it.

* CUDA supporting libraries are required for all the GPU-enabled orchestrators, so that's definitely nice to have, though I'm not familiar with its usage and don't know how many versions people will need to choose from.

* Python is also a must-have for most of the training jobs that will run on these containers, but we can't ship the latest 3 because it usually breaks the usual suspects (numpy, scipy) for a while due to CPython API deprecations. Having a container with 2 (latest) and 3 (latest - minor) could be interesting.

* DVC is also really nice to have, and we could ship the latest if that doesn't break anything, but it would be better yet to pin it to the major version to avoid incompatibilities.

* CML itself would always be latest, as we don't plan to make any breaking change, at least until we hit 1.0.0, right?

We could automatically ship containers with some tag tetrads like `cml-0-11-3-2` for `CML-CUDA-Python-DVC` if we don't find a better solution. Anyhow, it would be nice to test all the containers for correctness with some sort of touchstone workflow collection.

**Comment by DavidGOrtega** [comment]
> We could automatically publish containers with some tag tetrads like cml-0-11-3-2

I prefer to be explicit.

On thing also is that our py3 image is an image not a tag.

**Comment by 0x2b3bfa0** [comment]
> _I prefer to be explicit._
Excellent! Me too. 👍 

> _On thing also is that our py3 image is an image not a tag. Should we continue that way?_
If we choose this approach, I would suggest to migrate everything to tags for consistency and soft-deprecate the `cml-py3` image.

**Comment by 0x2b3bfa0** [comment]
Also, even if it looks a bit redundant, I think that it would be nice to offer a way of pinning the CML major version even if we still are below 1.0. This way, we have the freedom of introducing breaking changes cleanly if we ever need to.

```
docker://dvcorg/cml:0-python3-cuda10-dvc2
docker://dvcorg/cml:1-python4-cuda12-dvc3
```

It might look a bit too chatty, but this way users know exactly what to expect and that their update won't break anything unless they explicitly bump any of these major version.

**Comment by 0x2b3bfa0** [comment]
@DavidGOrtega, we're shipping Tensorflow with our containers, but people may be using something completely different on their workflows. Should we leave that choice to users, include another handful of popular frameworks, or just leave it as-is?

**Comment by 0x2b3bfa0** [comment]
@dmpetrov, it looks like we aren't using the [`cml-dev`](https://github.com/vgrengvir/cml/blob/master/docker/Dockerfile-dev) images, at least not on any of the repositories I'm familiar with. May we deprecate them in favor of the newly proposed tagging convention?

Once they become useful, we can start publishing images without a pinned major version, like `cml:1-cuda12-python4-dvc` for the sake of future predictions. The absence of a version number would denote that it's the latest version, but maybe we could also use another placeholder to make it explicit.

**Comment by 0x2b3bfa0** [comment]
When deprecating the old images, we might also want to pin the provider version [here](https://github.com/iterative/cml/blob/a5df22e505b6366b7a3b5b148e77737ef739d908/src/terraform.js#L61) and release a latest version with the old tags with that change and a deprecation warning message.

**Comment by 0x2b3bfa0** [comment]
# Unification and tagging proposal

## Images

### Hard deprecations (#383)
* [`cml-gpu-py3-cloud-runner`](https://hub.docker.com/r/dvcorg/cml-gpu-py3-cloud-runner)
* [`cml-gpu-cloud-runner`](https://hub.docker.com/r/dvcorg/cml-gpu-cloud-runner)
* [`cml-py3-cloud-runner`](https://hub.docker.com/r/dvcorg/cml-py3-cloud-runner)
* [`cml-cloud-runner`](https://hub.docker.com/r/dvcorg/cml-cloud-runner)

### Soft deprecations
* [`cml-py3`](https://hub.docker.com/r/dvcorg/cml-py3) images would be part of the new [`cml`](https://hub.docker.com/r/dvcorg/cml) base images
* [`cml-gpu-py3`](https://hub.docker.com/r/dvcorg/cml-gpu-py3) images would be part of the new  [`cml-gpu`](https://hub.docker.com/r/dvcorg/cml-gpu) base images
* [`cml-gpu-py3-dev`](https://hub.docker.com/r/dvcorg/cml-gpu-py3-dev) images would be released under the [`cml-test`](https://hub.docker.com/r/dvcorg/cml-test) name
* [`cml-dev`](https://hub.docker.com/r/dvcorg/cml-dev) images would be released as tags under the [`cml-test`](https://hub.docker.com/r/dvcorg/cml-test) name

### Updated images
* [`cml`](https://hub.docker.com/r/dvcorg/cml) from a generic Ubuntu base
* [`cml-gpu`](https://hub.docker.com/r/dvcorg/cml-gpu) from the official Nvidia Docker base
* [`cml-test`](https://hub.docker.com/r/dvcorg/cml-test) for testing and development with [GitHub Environments](https://docs.github.com/es/actions/reference/environments)

### Tag components

* CML
  * 0
* DVC
  * 1
  * 2
* BASE
  * 0
    * **CUDA 10.1**
    * **cuDNN 7**
    * Python 2.7
    * Ubuntu 18.04
  * 1
    * **CUDA 11.0.1**
    * **cuDNN 8**
    * Python 3.8
    * Ubuntu 20.04

_Note: items in bold won't be provided for non-GPU images._

### Tag example

* `cml-gpu:0-dvc-2-base-1` would refer to a GPU-enabled image with CML 0.X.X, DVC 2.X.X and the base 1 as per the list above.

## Rationale

This proposal tries to simplify the image offering by tying packages to known major versions, creating flexible labels for users to choose from, and reducing the total number of image names.

### Why separate `cml` and `cml-gpu`

Given that we're using totally different base images —ubuntu/(bionic|focal) for the former and nvidia/cuda for the latter— it might make sense to use separate names instead of tags to differentiate them. Also, there is a huge difference in their size (30 MB versus 1.11 GB), so we might want to take advantage of this naming scheme to differentiate both use cases as early as possible.

### Why pin major versions by default

Endorsing the usage of the `latest` tag won't allow us to (eventually) make a breaking change without disrupting the workflow of our existing users. On the other hand, forcing users to pin a minor version could keep us from delivering new useful features to existing users without requiring them to update their pinned versions.

### Why group system packages

Users might have very different requirements for their system and core packages depending on their stack, but a few of these setups are a lot more common than many others. Ideally, we should be offering a few curated combinations that are known to work correctly, and let the users choose fine-grained variations over that, be it by building images on top of ours or simply by installing additional packages when builiding each job.

### Why merge `cml-dev` into `cml-test`

I'm suggesting this additional action because, even if it's useful to have test, development and staging images for internal consumption, there wouldn't be any noticeable benefit in separating them beyond the label level. A single image might be enough for grouping all the transient builds that shouldn't matter for end users.

***

💡 _Note: this proposal has its roots in this [`Dockerfile`](https://github.com/vgrengvir/cml/blob/b95b38cba35c3fffae5130ac923b94a2da65c1a0/Dockerfile) and this [`release.yml`](https://github.com/vgrengvir/cml/blob/b95b38cba35c3fffae5130ac923b94a2da65c1a0/.github/workflows/release.yml) workflow._

**Comment by 0x2b3bfa0** [comment]
Tangentially, we probably should also consider the possibility of using [GitHub Environments](https://docs.github.com/es/actions/reference/environments) as mentioned above for deploying `cml-test` images with UID tags from any pull request and running cloud tests on them. It would be a good step towards fully automated testing of cloud runners.

**Comment by 0x2b3bfa0** [comment]
Given that image tags should be as stable as possible over time, we probably should discuss this proposal and triple-check everything before renaming anything.

🔔  @iterative/cml
