### ISSUE TITLE
Investigate GitHub Docker registry

### ISSUE THREAD

**Issue by dmpetrov** [iterative/cml#267]

**Comment by 0x2b3bfa0** [comment]
Linking to #217 to keep the container overhaul together...

**Comment by 0x2b3bfa0** [comment]
🔔  @casperdcl & @DavidGOrtega, what if we offer ghcr.io as an alternative/successor to Docker Hub? It looks really nice and might be more reliable than the latter.

Users would use addresses like `ghcr.io/iterative/cml:0-dvc2-base1-gpu` instead of `dvcorg/cml:0-dvc2-base1-gpu` to pull our images. What do you think?

**Comment by casperdcl** [comment]
I've mentioned this before.

The only potential problem I see is GitHub isn't primarily designed for docker image hosting so in the long run may be less feature-full & reliable.

**Comment by 0x2b3bfa0** [comment]
Given the current reliability and _featurefulness_ standards of Docker Hub, I think that we're good to go in that sense. 😉  You'll notice that I'm not a fan of [things like this](https://www.docker.com/blog/what-you-need-to-know-about-upcoming-docker-hub-rate-limiting), but still acknowledge that Docker Hub is the "standard" registry.
