### ISSUE TITLE
cml-runner - One shot delayed destroy below a graceful shutdown

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#413]
Runner should call destroy after some period of time that must be:
 - below the graceful shutdown time stablished by cloud vendors
 - good enough for the terraform provider to gather the logs to be presented to the user

**Comment by DavidGOrtega** [comment]
related to #22

**Comment by 0x2b3bfa0** [comment]
I was thinking about a different approach, but I don't know if it's a good idea: what would happen if we don't activate the destroy mechanism until the runner is ready, instead of waiting for an arbitrary number of seconds and then self-destroying our instance?

#### Cases

1. The runner doesn't get registered (ready status) due to a previous error, like a bad token.
2. The runner gets registered and then stops gracefully (or not) after the specified timeout.

#### Behaviors

1. The destroy process is performed by the same `terraform` process that spawned the runner.
2. The destroy process is performed by the runner itself, as happens actually in every case.

**Comment by 0x2b3bfa0** [comment]
It would be similar to the method [we're already applying](https://github.com/iterative/terraform-provider-iterative/blob/e1033ccc0cea4d8d288574eb4c893ae2738ed4dd/iterative/resource_machine.go#L156) for machines on the provider:

* Spawn the runner/machine instance.
* Wait until it's ready and registered.
* If the check times out, cleanup before exiting.

**Comment by DavidGOrtega** [comment]
I think it will just only add more code
With the one shot approach everything is the same and we caan just gather the logs.
The only benefit would be if by some reaason the credentials were not in shape for the runner to destory the machine but it thats the case the provider wont ever be able to do so

**Comment by 0x2b3bfa0** [comment]
My concern with hardcoded «good enough» times is that dealing with cloud resources is not an exact science, and relying on the off-instance provider for error shutdowns would allow us to decide when to remove the instance without worrying about it disappearing before retrieving the logs.

**Comment by DavidGOrtega** [comment]
in reality if you think about that once the one shot is implemented that timeout is unlikely to happen

**Comment by 0x2b3bfa0** [comment]
Thanks for the clarifications, @DavidGOrtega! Then, would an `await sleep(destroyTimeout);` before this block be enough?

https://github.com/iterative/cml/blob/8f9d4118f795a89c074721bc712432aae55e467f/bin/cml-runner.js#L94-L100

If I haven't missed anything, it would not be subject to the _graceful shutdown time stablished by cloud vendors_ because we haven't started the destroy process yet, and, in consequence, we're going to miss the `terraform destroy` logs.

By the way, do you know a more idiomatic alternative to the `sleep` function from the [`sleep-promise`](https://www.npmjs.com/package/sleep-promise) package?

**Comment by DavidGOrtega** [comment]
> before this block be enough?

Exactly, with a log warning that the destroy is in place

**Comment by 0x2b3bfa0** [comment]
##More context

* https://github.com/iterative/cml/pull/689#discussion_r823116188
