### ISSUE TITLE
cml-publish ERR_INVALID_URL

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#443]
Happened [here](https://github.com/iterative/cml-runner-base-case/runs/2094896195?check_suite_focus=true)

```sh
TypeError [ERR_INVALID_URL]: Invalid URL: 
    at onParseError (internal/url.js:257:9)
    at new URL (internal/url.js:333:5)
    at watermark_uri (/cml/src/utils.js:135:15)
    at CML.publish (/cml/src/cml.js:110:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async run (/cml/bin/cml-publish.js:25:18) {
  input: '',
  code: 'ERR_INVALID_URL'
```

**Comment by 0x2b3bfa0** [comment]
Unable to reproduce, but might be an error with https://asset.cml.dev

**Comment by 0x2b3bfa0** [comment]
I have been able to reproduce this issue artificially by mocking the [asset server](https://github.com/vgrengvir/cml/blob/b95b38cba35c3fffae5130ac923b94a2da65c1a0/src/utils.js#L67) and replying with an empty [`200`](https://developer.mozilla.org/es/docs/Web/HTTP/Status/200) response.

If this is a real issue, it's was probably caused on the backend.

**Comment by DavidGOrtega** [comment]
> If this is a real issue, it's was probably caused on the backend.

Yes. I have been noticing it from and you are right its in the backend

**Comment by 0x2b3bfa0** [comment]
I'll take a look once I have access to the function.

**Comment by 0x2b3bfa0** [comment]
I haven't been able to isolate any potential cause for this issue after reading the backend code and performing some tests.

**Comment by 0x2b3bfa0** [comment]
Excerpt from the [workflow run](https://github.com/iterative/cml-runner-base-case/runs/2094896195) linked on the [original post](https://github.com/iterative/cml/issues/443#issue-830086002) including log timestamps:

```console
Fri, 12 Mar 2021 12:24:48 GMT TypeError [ERR_INVALID_URL]: Invalid URL: 
Fri, 12 Mar 2021 12:24:48 GMT     at onParseError (internal/url.js:257:9)
Fri, 12 Mar 2021 12:24:48 GMT     at new URL (internal/url.js:333:5)
Fri, 12 Mar 2021 12:24:48 GMT     at watermark_uri (/cml/src/utils.js:135:15)
Fri, 12 Mar 2021 12:24:48 GMT     at CML.publish (/cml/src/cml.js:110:13)
Fri, 12 Mar 2021 12:24:48 GMT     at processTicksAndRejections (internal/process/task_queues.js:97:5)
Fri, 12 Mar 2021 12:24:48 GMT     at async run (/cml/bin/cml-publish.js:25:18) {
Fri, 12 Mar 2021 12:24:48 GMT   input: '',
Fri, 12 Mar 2021 12:24:48 GMT   code: 'ERR_INVALID_URL'
Fri, 12 Mar 2021 12:24:48 GMT }
```

**Comment by 0x2b3bfa0** [comment]
What puzzles me is that [there isn't any CloudWatch log with that timestamp](https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#logsV2:log-groups/log-group/$252Faws$252Flambda$252Fcml-image-upload) and, after correlating newer runs like [2096426611](https://github.com/iterative/cml-runner-base-case/runs/2096426611), I haven't found any noticeable clock skew.

It looks like the request didn't even trigger the lambda function and errored somewhere near API Gateway. I declare myself incapable of fixing this issue with a single sample, no means to reproduce it and no logs.

@DavidGOrtega, unless you want otherwise, I'm adding an user-friendly error with debug information just in case somebody is able to reproduce this issue in the future.
