### ISSUE TITLE
cml-tensorboard-dev bad credentials give a non descriptive error

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#479]
It returns an unhandled promise

**Comment by yngtdd** [comment]
I am wondering if I am hitting this bug within a GitHub Actions runner. It looks like there is a Javascript error being thrown by [cml-tensorboard-dev.js#L62](https://github.com/iterative/cml/blob/master/bin/cml-tensorboard-dev.js#L62). Is this due to Tensorboard authentication on my repository, by chance? 

<img width="1066" alt="Screen Shot 2021-06-07 at 12 19 14 PM" src="https://user-images.githubusercontent.com/84814700/121055110-f8e36b00-c78a-11eb-890f-d21495cae211.png">

**Comment by 0x2b3bfa0** [comment]
Sorry for the late reply, @yngtdd. If you're still facing this issue, maybe you can read the `stderr` and `stdout` temporary files to see what the problem is. 

https://github.com/iterative/cml/blob/6c451d965aaea2ad2b1812dd2a223def9ce87739/bin/cml-tensorboard-dev.js#L50

https://github.com/iterative/cml/blob/6c451d965aaea2ad2b1812dd2a223def9ce87739/bin/cml-tensorboard-dev.js#L52

**Comment by 0x2b3bfa0** [comment]
> _It returns an unhandled promise_

@DavidGOrtega, how can we reproduce this issue? Do you have an error log?
