### ISSUE TITLE
tutorial: NFS/volumes

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#561]
### Client-side sibling of https://github.com/iterative/terraform-provider-iterative/issues/89

 - [x] Security
 - [ ] External storage

Until we have ~https://github.com/iterative/terraform-provider-iterative/issues/107~ https://github.com/iterative/terraform-provider-iterative/issues/123 and https://github.com/iterative/terraform-provider-iterative/issues/89 we could offer some recipes that we have crafted as proposed solutions to some users in the Discord channel.
We would need to  create those simple scenarios in the docs as a FAQ?

**Comment by DavidGOrtega** [comment]
I think that the best idea is to put everything under collapsible blocks under a FAQ in the readme.

**Comment by 0x2b3bfa0** [comment]
https://dvc.org/doc/user-guide/managing-external-data#setting-up-an-external-cache?

**Comment by DavidGOrtega** [comment]
> https://dvc.org/doc/user-guide/managing-external-data#setting-up-an-external-cache?

@0x2b3bfa0 
> DVC requires that the project's cache is configured in the same external location as the data that will be tracked (external outputs).

We need the storage first? 🤔 Probably @casperdcl can help here

**Comment by casperdcl** [comment]
could still have CI cache `.dvc/cache`, if that's what you mean?

**Comment by DavidGOrtega** [comment]
@casperdcl Im not sure. What we originally did or hack in Discord was to attach a volume or an NFS storage.

**Comment by 0x2b3bfa0** [comment]
> _It should be technically feasible with something like this:_
> ```bash
> sudo apt install nfs-common
> sudo mount -t nfs EFS_IP_ADDRESS:/ MOUNTPOINT
> ```
> [**(From Discord)**](https://discord.com/channels/485586884165107732/728693131557732403/813885655201349642)

Using NFS-attached storage for a cache might not be an optimal solution due to latency and file transfer times. AWS EFS is quick, but not _that_ quick.

**Comment by 0x2b3bfa0** [comment]
DVC already supports cache over a variety of network transports and, if we plan to offer alternative solutions, they should be as local and as fast as possible. Probably block-based, mounted to the runner machine itself, and without any control over their lifecycle: exactly iterative/terraform-provider-iterative#89.

In the meanwhile, we can mention https://dvc.org/doc/user-guide/managing-external-data#setting-up-an-external-cache and, perhaps, tell users how to use an external NFS shared cache as per the hack above.

**Comment by 0x2b3bfa0** [comment]
Security requires a bit more attention than officially recommended workarounds: see https://github.com/iterative/terraform-provider-iterative/issues/125

**Comment by casperdcl** [comment]
> DVC already supports cache over a variety of network transports

are you talking about http://dvc.org/doc/user-guide/managing-external-data#examples? If that's the case, just to clarify... remote caches are only useful for external remote outputs (`dvc exp run --external`) which isn't a use case we're discussing atm afaik.

**Comment by shcheklein** [comment]
> So for our purposes DVC does not support cache over network

We would need to clarify "over network" here. I think we are on the same page, but to be precise - DVC cache supports anything that can be mounted as a volume and symlinked/copied from it into workspace. It means that it can be NAS (and we had teams with 70TB cache organized this way). But we can't do something like `dvc cache dir s3://dvc/storage` at the moment. This is what remotes are for now (though as far as I understand something like `dvc cache dir s3://dvc/storage` should be easy to implement).

**Comment by 0x2b3bfa0** [comment]
> _There is so much confusion on this point that even we often don't get it_ https://github.com/iterative/dvc.org/issues/520#issuecomment-855220404

Touché, @casperdcl! 😄  It looks like my cursory investigation wasn't enough to emit an educated opinion on this topic. 🙈

What I recommended on Discord — see https://github.com/iterative/cml/issues/561#issuecomment-852292788 for more information — was just a way of moving the local cache to a [NFS](https://en.wikipedia.org/wiki/Network_File_System) share, like the ones provided by [AWS](https://docs.aws.amazon.com/efs/latest/ug/creating-using-create-fs.html), [Azure](https://docs.microsoft.com/en-us/azure/storage/files/storage-files-how-to-create-nfs-shares) or [GCP](https://cloud.google.com/architecture/partners/netapp-cloud-volumes/creating-nfs-volumes).

It's relatively slow, but would allow users to reuse data between runs without having to query the DVC remote each time.

**Comment by 0x2b3bfa0** [comment]
> _There is so much confusion on this point that even we often don't get it_ https://github.com/iterative/dvc.org/issues/520#issuecomment-855220404

Touché, @casperdcl! 😄  It looks like my cursory investigation wasn't enough to emit an educated opinion on this topic. 🙈

What I recommended on Discord — see https://github.com/iterative/cml/issues/561#issuecomment-852292788 for more information — was just a way of moving the local cache to a [NFS](https://en.wikipedia.org/wiki/Network_File_System) share, like the ones provided by [AWS](https://docs.aws.amazon.com/efs/latest/ug/creating-using-create-fs.html), [Azure](https://docs.microsoft.com/en-us/azure/storage/files/storage-files-how-to-create-nfs-shares) or [GCP](https://cloud.google.com/architecture/partners/netapp-cloud-volumes/creating-nfs-volumes). It's slow for what users would expect of a cache <sup>[[citatation needed]](https://discord.com/channels/485586884165107732/563406153334128681/849948334176468992)</sup> but, at least, serves as an intermediate storage to avoid querying the mian DVC remote every time CML launches a new instance.

After reviewing the documentation, I noticed that `--external` would use data _in situ_ from a remote storage other than the DVC remote, without pushing it to the latter under any circumstances. That isn't what I wanted: the main DVC remote should always be the single source of truth for data, and caches, no matter how remote they are, should only be a convenience storage to accelerate and optimize data transfer operations.

**Comment by shcheklein** [comment]
> Does the DVC cache support read/write access from several instances at the same time? If not, the shared cache concept on iterative/terraform-provider-iterative#89 would not be feasible.

yes, it supports multiple clients

> Cache should not hold any data that isn't present on the DVC remote: it should be just a faster and potentially cheaper place to store a reasonably updated copy of the data.

it's a bit more nuanced. There are teams that don't use remotes at all :) But otherwise you are right.

**Comment by 0x2b3bfa0** [comment]
Thank you very much for shedding a bit of light on this, @shcheklein! 🙏🏼  

> _yes, it supports multiple clients_

Awesome! 🎉 

> _it's a bit more nuanced. There are teams that don't use remotes at all_

Makes sense after thinking on the details, though calling it _cache_ in the external data use case might not be too intuitive, even if the working principle is the same. 🙃

**Comment by 0x2b3bfa0** [comment]
> _as far as I understand something like `dvc cache dir s3://dvc/storage` should be easy to implement_

This is exactly what I was looking for! We don't need it for NFS, as it can be regarded as any other mounted filesystem, but it would be a great addition for other storage systems that can't be mounted at the system level in any meaningful way, like S3.

Before proposing the implementation of such a feature, I would also like to point out that we should ideally resort to mountable filesystems like HDFS or [Lustre](https://www.lustre.org/), which seem a good fit for this kind of use case:

> [_Many workloads such as machine learning, high performance computing (HPC), video rendering, and financial simulations depend on compute instances accessing the same set of data through high-performance shared storage_](https://aws.amazon.com/fsx/lustre/) (AWS FSx)

The pity is that this kind of solution is not supported on every cloud without a healthy dose of contrived manual deployments. As users will need to configure it by themselves, we probably need to consider availability and ease of use as part of the main comparison points.

**Comment by casperdcl** [comment]
Ok so action point:

@0x2b3bfa0 would be great if you could put together a performant NFS/volume example repo targeting use case of extremely large dependencies (>1TB, where users won't want to `dvc get`/`curl`/`aws cp` etc).

The checkpoint cache stuff is a different issue (#390).

**Comment by 0x2b3bfa0** [comment]
> _performant NFS_

May I add it as a relevant example for the Wikipedia page of [oxymoron](https://en.wikipedia.org/wiki/Oxymoron)? 😈  I'll follow up later with a comparison of all the solution we've talked about and some examples.

**Comment by 0x2b3bfa0** [comment]
## Storage requirements

1. As fast as the average DVC remote, at least.
2. Able to persist data between consecutive runs.
3. Accessible by several machines at the same time.
4. Available on all the public clouds we plan to support.

## General storage types

| | Ephemeral | Block | Object | File |
| -- | ------------|----- | ------ | ---- |
| **Can offer transfer speeds comparable to hard disks?** |✅ | ✅  | ✅  | 🟠|
| **Can be reused from different machines, one at a time?**   |🚫| ✅  | ✅  | ✅  |
| **Can be accessed by many machines at the same time?**  |🚫| 🚫  | ✅  | ✅   |

We<sup>[citation needed]</sup> have been using the word _volumes_ since the beginning of this issue — not to mention iterative/terraform-provider-iterative#89 — but [the concept of _volumes_](https://en.wikipedia.org/wiki/Volume_(computing)) is tightly related to block-based storage.

Unfortunately, [block-based storage](https://en.wikipedia.org/wiki/Block-level_storage) can't be accessed by several machines at the same time, so our only possible choices are [object-based storage](https://en.wikipedia.org/wiki/Object_storage) and some kinds of [distributed file-based storage](https://en.wikipedia.org/wiki/Clustered_file_system#Distributed_file_systems).

## Specific storage types

### Object-based
| | AWS | Azure | GCP |
| -- | -- | -- | -- |
| **Name** | [S3](https://aws.amazon.com/s3) | [Blob Storage](https://azure.microsoft.com/en-us/services/storage/blobs) | [Cloud Storage](https://cloud.google.com/storage) |
| **Alleged speed** | [12 GB/s](https://aws.amazon.com/premiumsupport/knowledge-center/s3-maximum-transfer-speed-ec2/) | [12.5 GB/s](https://azure.microsoft.com/es-es/blog/high-throughput-with-azure-blob-storage) | N/A |
| **Mountable with** | ✅ [s3fs-fuse](https://github.com/s3fs-fuse/s3fs-fuse) | ✅ [azure-storage-fuse](https://github.com/Azure/azure-storage-fuse) | ✅ [gcsfuse](https://github.com/GoogleCloudPlatform/gcsfuse/) |
| **Transit encryption** | ✅  [HTTPS](https://aws.amazon.com/s3/faqs) | ✅ [TLS 1.2](https://docs.microsoft.com/en-us/azure/storage/blobs/security-recommendations) | ✅  [TLS 1.3](https://cloud.google.com/security/encryption-in-transit) |
| **Authentication** | Token | Token | Service account |

### File-based
| | AWS | Azure | GCP |
| -- | -- | -- | -- |
| **Name** | [EFS](https://aws.amazon.com/efs) |[Files](https://azure.microsoft.com/en-us/services/storage/files) | [Filestore](https://cloud.google.com/filestore) |
| **Alleged speed** | [50 MB/s](https://docs.aws.amazon.com/efs/latest/ug/performance.html) | [60 MB/s](https://docs.microsoft.com/en-us/azure/storage/files/storage-files-scale-targets) | [100 MB/s](https://cloud.google.com/filestore/docs/performance) |
| **Mountable with** | ✅ NFSv4 | ✅ NFSv4 | ✅ NFSv3 |
| **Transit encryption** | ✅  [TLS 1.2](https://docs.aws.amazon.com/whitepapers/latest/efs-encrypted-file-systems/encryption-of-data-in-transit.html) | 🚫  [NO](https://docs.microsoft.com/bs-cyrl-ba/azure/storage/files/files-nfs-protocol#security) |  N/A |
| **Authentication** | 🚫 [NO](https://docs.aws.amazon.com/efs/latest/ug/NFS-access-control-efs.html) | N/A | 🚫 [NO](https://cloud.google.com/filestore/docs/access-control) |

## Recommended reads

* [Why NFS Sucks](https://www.kernel.org/doc/ols/2006/ols2006v2-pages-59-72.pdf)

**Comment by 0x2b3bfa0** [comment]
🔔  @iterative/cml, examples to follow as soon as I make sure that nobody has a personal preference for NFS. ⚔️

**Comment by 0x2b3bfa0** [comment]
# Draft
_(à la Mystical Job Machine, will revisit later)_

**Comment by 0x2b3bfa0** [comment]
Note: requires additional discussion and, probably, will be merged with https://github.com/iterative/terraform-provider-iterative/issues/89

**Comment by casperdcl** [comment]
related: https://github.com/iterative/dvc.org/pull/2587

**Comment by 0x2b3bfa0** [comment]
Mounting FUSE devices inside a container is still not possible without the `SYS_ADMIN` flag and some extra privileges:
* https://github.com/docker/for-linux/issues/321
* https://github.com/kubernetes/kubernetes/issues/7890#issuecomment-821251595

This should change once container runtimes start to allow unprivileged userspace mounts as per https://github.com/torvalds/linux/commit/4ad769f3c346

**Comment by 0x2b3bfa0** [comment]
In the meantime, we can mount the filesystem at the instance level (on machines) or with additional privileges (on containers), but this could have [a negative impact](https://blog.trailofbits.com/2019/07/19/understanding-docker-container-escapes/) on container isolation.

**Comment by 0x2b3bfa0** [comment]
The question is: does attaching object-based or file-based storage make any sense if we take into account the limitations exposed on iterative/dvc.org#2587?

Attaching this kind of storage would be approximately as practical as pulling/pushing data with `dvc` to any of the supported remotes, and the only difference would be that data manipulation would be done _in situ_ without requiring a local scratchpad.

**Comment by 0x2b3bfa0** [comment]
> _Getting peaks of ~500 MiB/s (yes, the ISO 80000-13 ones) on S3 with a beefy c5a.24xlarge instance after fine–tuning rclone settings._

Closed with https://github.com/iterative/terraform-provider-iterative/pull/237

**Comment by 0x2b3bfa0** [comment]
https://github.com/iterative/cml-playground/pull/247
