### ISSUE TITLE
Github actions ephemeral registration  option.

### ISSUE THREAD

**Issue by DanielBarnes** [iterative/cml#724]
Adding in github's [new ephhemeral flag](https://github.blog/changelog/2021-09-20-github-actions-ephemeral-self-hosted-runners-new-webhooks-for-auto-scaling/) when running the [config.sh](https://github.com/iterative/cml/blob/2e9a21ddb4b4eb1261a75ba72f89b98b1972d063/src/drivers/github.js#L227-L237) could be of benefit.

For your consideration.

**Comment by 0x2b3bfa0** [comment]
Thanks!

We support this functionality with `cml-runner --single` since #393, by making use of the undocumented `--once` option, which is [fully equivalent](https://github.com/actions/runner/blob/f259e5706fd354b1bf6b54ea0a8705a5eaff48bf/src/Runner.Listener/Runner.cs#L237) to the newly introduced [`Runner.Listener configure --epehemeral`](https://github.com/actions/runner/blob/cf87c55557432fd06fdae6ec1b7641011316ec42/src/Misc/layoutroot/config.sh#L80) option from https://github.com/actions/runner/pull/660.

https://github.com/iterative/cml/blob/2e9a21ddb4b4eb1261a75ba72f89b98b1972d063/src/drivers/github.js#L239

Even if they're fully equivalent, the latter [is going to be deleted](https://github.com/actions/runner/blob/f259e5706fd354b1bf6b54ea0a8705a5eaff48bf/src/Runner.Listener/Runner.cs#L237) and we should use the new option instead.

**Comment by DanielBarnes** [comment]
Shouldn't this be a more robust option when handling any errors?

I didn't look too deep but their change (I hope)/a quick glance at the changes, it is more than a simple name swap, pretty sure it passes the flag when first reaching out to GitHub so that the GitHub side knows it's only good for one job?

https://github.com/actions/runner/blob/849d81a8cd745ce1217732275fa83107582beac5/src/Runner.Listener/Runner.cs#L469-L480

**Comment by 0x2b3bfa0** [comment]
> [The GitHub Actions service will then automatically de-register the runner after it has processed one job.](https://docs.github.com/en/actions/hosting-your-own-runners/autoscaling-with-self-hosted-runners#using-ephemeral-runners-for-autoscaling)

* https://github.com/actions/runner/pull/660
