### ISSUE TITLE
cml-runner AWS spot instances being targeted in only one availability zone

### ISSUE THREAD

**Issue by dragarok** [iterative/cml#833]
I have been using cml-runner in my workflow for some time now. When I set region to us-east-2 in cml-runner command, it looks for availability only in us-east-2a. But, today I noticed that there were spot instances available frequently in other availability regions such as us-east-2b. Is there something I am missing or a fix that I can include into the current scenario?

**Comment by dacbd** [comment]
There is a fix coming I plan to finish try and finish it by the weekend.

https://github.com/iterative/terraform-provider-iterative/pull/323

Then: https://github.com/iterative/cml/pull/831

But really after the the TPI PR (the first link) is merged and published you can set the availability zone via region

So instead of `us-west-2` you can put `us-west-2a` or `us-west-2b` etc

🤞 It should be good for use by the end of the week, but I can't promise anything other than soon™[^1]

[^1]: maybe 😄

**Comment by dacbd** [comment]
@dragarok tpi patch has been released you can target an availability zone as described above.
https://github.com/iterative/terraform-provider-iterative/releases/tag/v0.9.3

**Comment by alokehp** [comment]
> @dragarok tpi patch has been released you can target an availability zone as described above. https://github.com/iterative/terraform-provider-iterative/releases/tag/v0.9.3

Tested and it works. Thank you for the update.

**Comment by casperdcl** [comment]
closing as solve above; thanks!
